language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  global:
    - TZ=Asia/Kolkata

before_script:
  - echo 'Asia/Kolkata' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo ln -snf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

script:
  - date
  - cargo build --all
  - cargo test --all