[package]
name = "tztail"
version = "1.0.0"
authors = ["Aswin Karthik <aswinkarthik93@gmail.com>"]

[dependencies]
regex = "1"
hourglass = "0.*"
chrono = "0.4"
chrono-tz = "0.5"

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]